## libraries are nothinhg but collection of functions and classes

In [1]:
#pip install module/libraryname

In [2]:
# import module/libraryname

In [3]:
# from libraryname import module1,module2,module4

# modules :

## 1.Random:-

In [1]:
import random

In [2]:
# random() will generate a random number between 0 and 1 float values

In [4]:
random.random()

0.6118039350957166

In [6]:
# randint() will genrate a random intiger values between a and b

In [14]:
random.randint(1,3)

2

In [15]:
random.randint(1,3)

1

In [16]:
import random as x

In [17]:
x.random()

0.34663065272894655

## 2.Randrange:-

In [18]:
# randrange () will genrate a random values between a spesified values

In [25]:
x.randrange(1,3)

1

## uniform:-

In [26]:
# uniform will generate a float value between two numbers will uniform distribution

In [27]:
x.uniform(1,4)

3.2569052357991493

## sample()

In [ ]:
# sample() will 

In [30]:
x.sample([1,2,3,4,],k=2)

[2, 4]

In [32]:
x.sample([1,2,3,4,5,6,7,8,9,1,34,44,4,5,3,3],k=7)

[34, 3, 1, 8, 3, 4, 44]

In [33]:
x.sample([1,2,3,4],k=5)

ValueError: Sample larger than population or is negative

## choices()

In [49]:
#choices() will choose the random values with repitation

In [34]:
x.sample("abc",k=2)

['c', 'b']

In [48]:
x.choices("abc",k=2)

['b', 'b']

In [50]:
x.choices("abc",k=10)

['b', 'a', 'b', 'b', 'b', 'b', 'a', 'c', 'a', 'a']

## shuffle()

In [51]:
z=["a","b","c"]
x.shuffle(z)

In [52]:
z

['a', 'c', 'b']

##    seed()

In [54]:
x.seed(10)
x.randint(1,100)

74

In [57]:
x.seed()
x.randint(1,100)

99

In [58]:
x.seed()
x.randint(1,100)

11

In [60]:
x.seed(20)
x.randint(1,100)

93

# creating your own module

ModuleNotFoundError: No module named 'maa'

# Numpy :

In [1]:
# we can create an array 
# we can create n-dimentional array object.
# it provides lots of tools.


### 1.array :

In [2]:
# array is a collection of similar type of data.
# array containes homoginious data
# arrays are mutable
# array has each element have an index value.
# array also consider as odered.
# array containes duplicate elements 

### pip instal numpy

## creating an array

In [3]:
import numpy as np

In [4]:
x=np.array(5)

In [5]:
type(x)

numpy.ndarray

In [6]:
x.ndim  # to get the rank of an array.

0

In [7]:
x1=np.array([5])

In [8]:
x1

array([5])

In [9]:
x1=np.array([5,6,7,8,9,0])

In [10]:
x1

array([5, 6, 7, 8, 9, 0])

In [11]:
x1.ndim

1

In [16]:
x2=np.array([[5,6,7],[8,9,10],[11,12,13]])

In [17]:
x2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [18]:
x2.ndim

2

In [19]:
x3=np.array([[[[[5,6,7],[7,8,9]]]]])

In [20]:
x3

array([[[[[5, 6, 7],
          [7, 8, 9]]]]])

In [21]:
x3.ndim

5

### (dtype) used to change the data type (string,int,complex,float)

In [26]:
x1=np.array([5,6,7,8,9,10],dtype=str)

In [24]:
x1

array(['5', '6', '7', '8', '9', '10'], dtype='<U2')

In [27]:
x1=np.array([5,6,7,8,9,10],dtype=complex)

In [28]:
x1

array([ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j])

In [29]:
x1=np.array([5,6,7,8,9,10],dtype=np.int8)

In [30]:
x1

array([ 5,  6,  7,  8,  9, 10], dtype=int8)

In [33]:
x1=np.array([5,6,7,8,9,10],dtype=np.bool_)

In [34]:
x1

array([ True,  True,  True,  True,  True,  True])

### (ndmin) is used to create a dimentions min=0 & max=32


In [35]:
x1=np.array([5,6,7,8,9,10],dtype=int,ndmin=3)

In [36]:
x1

array([[[ 5,  6,  7,  8,  9, 10]]])

In [37]:
x1=np.array([5,6,7,8,9,10],dtype=int,ndmin=10)

In [38]:
x1

array([[[[[[[[[[ 5,  6,  7,  8,  9, 10]]]]]]]]]])

In [39]:
x1=np.array([5,6,7,8,9,10],dtype=int,ndmin=32)

In [40]:
x1

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 5,
                                       6,
                                       7,
                                       8,
                                       9,
                                      10]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [ ]:
#

In [45]:
e=np.array([1,6,0,8,9.0+2j,"10"])

In [46]:
e

array(['1', '6', '0', '8', '(9+2j)', '10'], dtype='<U64')

In [47]:
e.dtype

dtype('<U64')

### (shape) it will showa many rows and columns are present in an array

In [49]:
x1.shape

(1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 6)

In [50]:
e=np.array([3])

In [51]:
e

array([3])

In [54]:
type(e)

numpy.ndarray

In [55]:
a=np.array([[5,6,7],[8,9,10],[4,5,6]])

In [56]:
a.shape

(3, 3)

In [57]:
x3=np.array([[[[[5,6,7],[7,8,9]]]]])

In [58]:
x3.shape

(1, 1, 1, 2, 3)

In [59]:
b=np.array([4,5,6,7,8,9,10,100])

In [61]:
b[0]

4

In [62]:
b[-1]

100

In [63]:
b[:2]

array([4, 5])

In [64]:
b[0]=100

In [65]:
b

array([100,   5,   6,   7,   8,   9,  10, 100])

# Advance function to create an array

### 1.Zeros:-

In [8]:
import numpy as np

In [9]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 2.one's:-

In [2]:
# one's is also a function we can create n dimentional object when all the elements will be one's

In [ ]:
a1=np.ones()

### 3.np.full():

In [3]:
# np.full((3,3),11,)if we want all with same numbers this in 3 rows and 3 columns

In [11]:
a3=np.full((3,4),81)

a3

In [12]:
a3

array([[81, 81, 81, 81],
       [81, 81, 81, 81],
       [81, 81, 81, 81]])

### 4.np.eye():

In [5]:
# np.eye(10)

In [15]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 5.np.diag():

In [6]:
# np.diag([2,3,4,5])

In [17]:
q=np.diag([10,11,12])

In [18]:
q

array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [19]:
np.diag(q)

array([10, 11, 12])

### 6.np.arange():

In [21]:
f=np.arange(10,21)

In [22]:
f

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
f.ndim

1

In [24]:
f.shape

(11,)

In [25]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [26]:
np.arange(10,21,3)

array([10, 13, 16, 19])

In [28]:
# reverse the value

x="abcdef"
x[::-1]

'fedcba'

In [29]:
for y in x[::-1]:
    print(y)

f
e
d
c
b
a


In [53]:
for y in range(1,10,3):
    print(y)

1
4
7


In [31]:
for y in range(len(x)-1,-1,-1):
    print(x[y])

f
e
d
c
b
a


### 7.linspace:-

In [33]:
np.linspace(1,10,2)

array([ 1., 10.])

In [34]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [35]:
np.linspace(1,10,dtype=int)

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

 this is not a function it is a module



In [37]:
np.random.random((2,3))

array([[0.88256493, 0.83490665, 0.14086979],
       [0.47760458, 0.07316543, 0.43816064]])

In [38]:
import time

In [39]:
x=time.time()
y=np.arange(1,10000000)*2
z=time.time()
print(z-x)

0.04694199562072754


In [40]:
x=time.time()
l=[]
for y in range(1,10000000):
    l.append(y*2)
z=time.time()
print(z-x)

3.0938868522644043


### acces the elements inside an n dimentional array

In [41]:
#n=1

In [42]:
x=np.arange(1,9)

In [43]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
x[0]

1

In [45]:
x[-1]

8

In [46]:
#n=2

In [47]:
z=np.random.random((3,4))

In [48]:
z

array([[0.13415455, 0.96023201, 0.5252351 , 0.27847626],
       [0.84900967, 0.93927577, 0.96002134, 0.61884704],
       [0.95920503, 0.55547598, 0.41117497, 0.53527163]])

In [1]:
import numpy as np

In [2]:
x=np.arange(1,10)

In [3]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.shape

(9,)

In [5]:
y=x.reshape(3,3)

In [6]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Accessing elements in 2 dimentional arrays

## they are 3 types:

### 1. intiger based indexing   2. slicing based indexing    3. boolean based indexing

### 1.slicing based indexing

#### whenever we are getting from the original array with the help of sub array

#### sub array and original array in the same dimention

In [7]:
y[0:1,0:]

array([[1, 2, 3]])

In [8]:
y[1:,0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
z=np.arange(1,21).reshape(5,4)

In [11]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [12]:
z[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [13]:
z[0,0]=1000

In [14]:
z

array([[1000,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12],
       [  13,   14,   15,   16],
       [  17,   18,   19,   20]])

### 2. intiger based indexing

In [15]:
z[[2,2,0],[2,3,0]]

array([  11,   12, 1000])

#### intiger based indexing can choose any position



#### the sub array copy the original array

#### whenever you getting sub array lower dimention

## how apply mathematical operations to an array

### +,-,/,*, will be performed element wise

In [18]:
a=np.arange(1,9).reshape(4,2)

In [19]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
b=np.arange(9,17).reshape(4,2)

In [21]:
b

array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [22]:
c=np.add(a,b)

In [23]:
c

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24]])

In [24]:
d=np.multiply(a,b)

In [25]:
d

array([[  9,  20],
       [ 33,  48],
       [ 65,  84],
       [105, 128]])

In [26]:
e=np.subtract(a,b)

In [27]:
e

array([[-8, -8],
       [-8, -8],
       [-8, -8],
       [-8, -8]])

In [39]:
# comparision operators ---  >,<,<=,>= etc are also performed element wise

In [42]:
x=np.full((9,2),11)

In [43]:
x

array([[11, 11],
       [11, 11],
       [11, 11],
       [11, 11],
       [11, 11],
       [11, 11],
       [11, 11],
       [11, 11],
       [11, 11]])

### 3.boolean based indexing

#### based on condition.true or false

In [ ]:
# it creates copy of an array

In [29]:
d>e

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [30]:
c<b

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [31]:
b<e

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [32]:
b>e

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [33]:
b<=e

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [34]:
d[d%2==0]

array([ 20,  48,  84, 128])

In [35]:
d

array([[  9,  20],
       [ 33,  48],
       [ 65,  84],
       [105, 128]])

In [36]:
(d%5==0) | (d%7==0) # |-->or   

array([[False,  True],
       [False, False],
       [ True,  True],
       [ True, False]])

In [37]:
(d%5==0) & (d%7==0)  # &---> and

array([[False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [113]:
import numpy as np

In [114]:
# np.any()
# np.all()

In [115]:
x=np.arange(1,21).reshape(3,4)

ValueError: cannot reshape array of size 20 into shape (3,4)

# *---- Dot product

In [116]:
x=np.arange(0,6).reshape(3,2)

In [117]:
y=np.arange(0,6).reshape(3,2)

In [118]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [119]:
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [120]:
x*y

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [121]:
y.T

array([[0, 2, 4],
       [1, 3, 5]])

In [122]:
np.dot(x,y.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

# Reduction functions:

### 1.sum:()

In [123]:
# sum()-- it will sum all the values inside a array

In [124]:
x2=np.arange(0,9).reshape(3,3)

In [125]:
x2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
np.sum(x2)

36

In [127]:
np.sum(x2,axis=0)  # 0--colimn
# it will give you column wise total

array([ 9, 12, 15])

In [128]:
np.sum(x2,axis=1)   # 1--rows
# it will give you row wise total

array([ 3, 12, 21])

### 2.prod:()

#### it will return the product of vazlues in array

In [129]:
np.prod(x2)

0

In [130]:
np.prod(x2,axis=0)

array([ 0, 28, 80])

In [131]:
np.prod(x2,axis=1)

array([  0,  60, 336])

### 3.min:()

In [132]:
np.min(x2,axis=0)

array([0, 1, 2])

In [135]:
np.max(x2,axis=1)

array([2, 5, 8])

### 4.max:()

In [136]:
np.max(x2,axis=0)

array([6, 7, 8])

### 5.nan:()-- not any number

#### *nan's defaulft datatype is float

#### *it is used to create an empty array

#### *it is not a string

#### * we cannot perform sum and product in nan fun

#### * nanas type() is used convert data type

In [137]:
x2=x2.astype(float)

In [138]:
x2

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [139]:
x2[1,1]=np.nan

In [140]:
x2

array([[ 0.,  1.,  2.],
       [ 3., nan,  5.],
       [ 6.,  7.,  8.]])

In [141]:
np.sum(x2)

nan

In [142]:
np.prod(x2)

nan

In [143]:
np.nansum(x2)

32.0

In [144]:
np.nanprod(x2)

0.0

In [145]:
x3=np.arange(0,9,dtype=float).reshape(3,3)

In [146]:
x3[0,1]=np.nan
x3[1,2]=np.nan

In [147]:
x3

array([[ 0., nan,  2.],
       [ 3.,  4., nan],
       [ 6.,  7.,  8.]])

In [148]:
np.isnan(x3)

array([[False,  True, False],
       [False, False,  True],
       [False, False, False]])

 x3[np.isnan(x3)]=10

In [149]:
x3[np.isnan(x3)]=10

### 6.inf:()

#### representing infinate value

In [150]:
x3[0,0]=np.inf

In [151]:
x3

array([[inf, 10.,  2.],
       [ 3.,  4., 10.],
       [ 6.,  7.,  8.]])

In [152]:
 np.isinf(x3)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

### 7.cumsum()-->cumulative sum

In [153]:
x=np.array([1,2,3,4])

In [154]:
np.cumsum(x)

array([ 1,  3,  6, 10], dtype=int32)

In [155]:
np.cumsum(y)

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

### 8.cumprod:()

In [156]:
np.cumprod(x)

array([ 1,  2,  6, 24], dtype=int32)

np.cumprod(x,axis=0)

In [157]:
np.cumprod(x,axis=0)

array([ 1,  2,  6, 24], dtype=int32)

In [158]:
np.cumprod(y)

array([0, 0, 0, 0, 0, 0], dtype=int32)

In [159]:
y=np.arange(0,6).reshape(3,2)

In [160]:
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [161]:
y=y.astype(float)

In [162]:
y[1,1]=np.nan

In [163]:
y

array([[ 0.,  1.],
       [ 2., nan],
       [ 4.,  5.]])

In [164]:
np.cumsum(y)

array([ 0.,  1.,  3., nan, nan, nan])

In [165]:
np.nancumsum(y)

array([ 0.,  1.,  3.,  3.,  7., 12.])

In [166]:
np.cumprod(y)

array([ 0.,  0.,  0., nan, nan, nan])

In [167]:
np.nancumprod(y)

array([0., 0., 0., 0., 0., 0.])

### 9.flatten:()

#### * it will convert all the rows into a single row

#### * it will give you a new array

#### * it is the copy of the array. it will not change the array.

In [168]:
y.flatten()

array([ 0.,  1.,  2., nan,  4.,  5.])

In [169]:
y

array([[ 0.,  1.],
       [ 2., nan],
       [ 4.,  5.]])

### 10.ravel()

In [170]:
y.ravel()

array([ 0.,  1.,  2., nan,  4.,  5.])

In [171]:
y

array([[ 0.,  1.],
       [ 2., nan],
       [ 4.,  5.]])

In [172]:
y[0]=1000

In [173]:
y

array([[1000., 1000.],
       [   2.,   nan],
       [   4.,    5.]])

In [174]:
y[0,0]=100

In [175]:
y

array([[ 100., 1000.],
       [   2.,   nan],
       [   4.,    5.]])

### 11.round()

In [176]:
x=np.array([1.3456 , 4.57836536 , 5.457354658])

In [177]:
x

array([1.3456    , 4.57836536, 5.45735466])

In [178]:
np.round(x,3)

array([1.346, 4.578, 5.457])

In [179]:
np.round(x,1)

array([1.3, 4.6, 5.5])

In [181]:
np.round(x)

array([1., 5., 5.])

### 12.ceil:()

In [184]:
np.ceil(x)

array([2., 5., 6.])

### 13.floor()

In [186]:
np.floor(x)

array([1., 4., 5.])

### 14.log()

In [188]:
z=np.array([2,3,4,5,6,-3,9])

In [189]:
np.sqrt(z)

C:\Users\Ravi Kumar\AppData\Local\Temp\ipykernel_19916\2292707815.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(z)


array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
              nan, 3.        ])

### 15.sqrt()---square root

In [190]:
np.log(z)

C:\Users\Ravi Kumar\AppData\Local\Temp\ipykernel_19916\2047398432.py:1: RuntimeWarning: invalid value encountered in log
  np.log(z)


array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
              nan, 2.19722458])

In [191]:
3**(1/2)

1.7320508075688772